#!/usr/bin/env node
/* Merges per-position research JSON (data/raw/*.json) into app/players.js + data/players.json.
   Usage: node scripts/build-data.js [rawDir]  */
const fs = require('fs');
const path = require('path');
const E = require('../app/engine.js');

const rawDir = process.argv[2] || path.join(__dirname, '..', 'data', 'raw');
const files = fs.readdirSync(rawDir).filter(f => /^data_.*\.json$/.test(f));
const TEAMS = new Set('ARI ATL BAL BUF CAR CHI CIN CLE DAL DEN DET GB HOU IND JAX KC LV LAC LAR MIA MIN NE NO NYG NYJ PHI PIT SF SEA TB TEN WAS'.split(' '));
const FIX = { JAC: 'JAX', WSH: 'WAS', LA: 'LAR', OAK: 'LV', SD: 'LAC', STL: 'LAR', GNB: 'GB', KAN: 'KC', NWE: 'NE', NOR: 'NO', SFO: 'SF', TAM: 'TB', LVR: 'LV' };
const NUM = ['adp', 'tier', 'bye', 'pass_yds', 'pass_td', 'pass_int', 'rush_att', 'rush_yds', 'rush_td', 'rec', 'rec_yds', 'rec_td', 'fumbles', 'proj_pts_halfppr'];

let all = [];
const warnings = [];
for (const f of files) {
  let d;
  try { d = JSON.parse(fs.readFileSync(path.join(rawDir, f), 'utf8')); } catch (e) { warnings.push(`${f}: invalid JSON (${e.message})`); continue; }
  const list = Array.isArray(d) ? d : (d.players || []);
  list.forEach(p => {
    const q = {};
    q.name = String(p.name || '').trim();
    q.pos = String(p.pos || '').toUpperCase().replace('DST', 'DEF').replace('D/ST', 'DEF');
    q.team = String(p.team || '').toUpperCase().trim();
    q.team = FIX[q.team] || q.team;
    if (!TEAMS.has(q.team) && q.team !== 'FA') warnings.push(`${f}: unknown team "${q.team}" for ${q.name}`);
    NUM.forEach(k => { if (p[k] != null && p[k] !== '') q[k] = Number(p[k]) || 0; });
    q.status = p.status || 'healthy';
    q.notes = String(p.notes || '').trim();
    q.confidence = p.confidence || '';
    if (!q.name || !E.POS.includes(q.pos)) { warnings.push(`${f}: skipped ${JSON.stringify(p).slice(0, 80)}`); return; }
    // Sanity: stat line vs claimed points (half PPR).
    const calc = E.projectPoints(q, E.PRESETS.yahoo_half.scoring);
    if (q.pos !== 'K' && q.pos !== 'DEF' && q.proj_pts_halfppr && Math.abs(calc - q.proj_pts_halfppr) > 25)
      warnings.push(`${q.name}: stat line gives ${calc} but proj_pts ${q.proj_pts_halfppr}`);
    all.push(q);
  });
}
// Dedup by id (keep the entry with more stats)
const byId = {};
all.forEach(p => {
  const id = E.playerId(p);
  if (!byId[id] || Object.keys(p).length > Object.keys(byId[id]).length) byId[id] = p;
});
all = Object.values(byId);
// Apply news overrides if present (data/raw/news.json: [{player, status, impact, detail}])
const newsFile = path.join(rawDir, 'news.json');
if (fs.existsSync(newsFile)) {
  try {
    const news = JSON.parse(fs.readFileSync(newsFile, 'utf8'));
    const items = Array.isArray(news) ? news : (news.items || []);
    const idx = {}; all.forEach(p => { idx[E.normalizeName(p.name)] = p; });
    items.forEach(it => {
      const p = idx[E.normalizeName(it.player)];
      if (!p) return;
      const note = `${it.status || it.impact}: ${it.detail || ''}`.trim();
      if (it.impact === 'out-season' || /out.*season|season.ending|torn (acl|achilles)|ir\b.*season/i.test(String(it.detail))) {
        if (p.status !== 'out-season') { p.status = 'out-season'; p.notes = (note + ' ' + p.notes).trim(); warnings.push(`NEWS: ${p.name} marked out-season`); }
      } else if (it.status && p.status === 'healthy' && /injur|suspend|holdout|question|doubtful|pup/i.test(it.status + ' ' + it.impact)) {
        p.status = it.impact === 'out-weeks' ? 'injured-short' : (/suspend/i.test(it.status + it.impact) ? 'suspended' : 'questionable');
        p.notes = (note + ' ' + p.notes).trim();
      }
    });
  } catch (e) { warnings.push('news.json invalid: ' + e.message); }
}
// Out-for-season players: keep in pool (so they can be marked drafted) but zero their projection.
all.forEach(p => { if (p.status === 'out-season') { NUM.slice(3).forEach(k => { if (k !== 'adp' && k !== 'tier' && k !== 'bye') p[k] = 0; }); p.proj_pts_halfppr = 0; p.adp = Math.max(p.adp || 300, 250); } });
all.sort((a, b) => (a.adp || 300) - (b.adp || 300));

const out = { generated: new Date().toISOString(), season: 2026, scoring_basis: 'half-PPR projections; points recomputed in-app from stat lines', players: all };
fs.mkdirSync(path.join(__dirname, '..', 'data'), { recursive: true });
fs.writeFileSync(path.join(__dirname, '..', 'data', 'players.json'), JSON.stringify(out, null, 1));
let notes = {};
const sn = path.join(rawDir, 'strategy_notes.json');
if (fs.existsSync(sn)) { try { notes = JSON.parse(fs.readFileSync(sn, 'utf8')); } catch (e) { warnings.push('strategy_notes.json invalid'); } }
const js = `// Generated by scripts/build-data.js on ${out.generated}. Do not edit by hand; edit data/raw/*.json and rebuild.\n` +
  `window.PLAYER_DATA = ${JSON.stringify(out)};\n` +
  `window.STRATEGY_NOTES = ${JSON.stringify(notes)};\n`;
fs.writeFileSync(path.join(__dirname, '..', 'app', 'players.js'), js);
const counts = {}; all.forEach(p => { counts[p.pos] = (counts[p.pos] || 0) + 1; });
console.log('players:', all.length, JSON.stringify(counts));
if (warnings.length) { console.log('warnings (' + warnings.length + '):'); warnings.slice(0, 60).forEach(w => console.log(' -', w)); }
